/* loescht*/
/* user */
DROP USER IF EXISTS vereinAdmin;

/* db */
DROP DATABASE IF EXISTS fussballVerein;

/* alle tables */
DROP TABLE Mannschaft CASCADE CONSTRAINTS;
DROP TABLE Person CASCADE CONSTRAINTS;
DROP TABLE Spiel CASCADE CONSTRAINTS;
DROP TABLE Spieler CASCADE CONSTRAINTS;
DROP TABLE SpielerInMannschaft CASCADE CONSTRAINTS;
DROP TABLE Standort CASCADE CONSTRAINTS;
DROP TABLE Trainer CASCADE CONSTRAINTS;
DROP TABLE TrainerAssistenten CASCADE CONSTRAINTS;
DROP TABLE Angestellter CASCADE CONSTRAINTS;
DROP TABLE BeteiligteSpieler CASCADE CONSTRAINTS;
DROP TABLE ChefTrainer CASCADE CONSTRAINTS;
DROP TABLE Kapitän CASCADE CONSTRAINTS;
DROP TABLE Mitglied CASCADE CONSTRAINTS;
DROP TABLE Fan-Club CASCADE CONSTRAINTS;
DROP TABLE Obmann CASCADE CONSTRAINTS;
DROP TABLE Zeitraum CASCADE CONSTRAINTS;